### PR TITLE
fix: bounds check before seeking from archive fsm

### LINKED ISSUE #102: Found panic in `rc-zip-sync/src/read_zip.rs:214` while fuzzing
**Describe the bug**

After watching your video about sans-io I wanted to take a look at the implementation of the rc-zip crates. Seeing that you have added fuzzing support, I thought to run the fuzzer on the latest version of the code (`8a09a9d7d70757c0ca1c084c2be5d34ae0038a58` at the time of writing).

The fuzzer produced a crashing input for [`rc-zip-sync/src/read_zip.rs:214`](https://github.com/bearcove/rc-zip/blob/8a09a9d7d70757c0ca1c084c2be5d34ae0038a58/rc-zip-sync/src/read_zip.rs#L213-L215).

**To Reproduce**

```console
$ mkdir -p fuzz/artifacts/no_panic
$ echo "UAoGUFBLBgcGBgZGBgZQ0SbQUFDQSwVQUEsFBtFlZf///////wAAAAAAAAAAACQ=" | base64 -d > fuzz/artifacts/no_panic/crash-7bc4fbe51eb6a77c6a8996e7d2d47ad1e44727b6
$ cargo +nightly fuzz run no_panic fuzz/artifacts/no_panic/crash-7bc4fbe51eb6a77c6a8996e7d2d47ad1e44727b6
    Finished `release` profile [optimized + debuginfo] target(s) in 0.05s
    Finished `release` profile [optimized + debuginfo] target(s) in 0.05s
     Running `fuzz/target/x86_64-unknown-linux-gnu/release/no_panic -artifact_prefix=/home/pigeonf/reading/rc-zip/fuzz/artifacts/no_panic/ fuzz/artifacts/no_panic/crash-7bc4fbe51eb6a77c6a8996e7d2d47ad1e44727b6`
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1946761
INFO: Loaded 1 modules   (126305 inline 8-bit counters): 126305 [0x5592a147a200, 0x5592a1498f61),
INFO: Loaded 1 PC tables (126305 PCs): 126305 [0x5592a1498f68,0x5592a1686578),
fuzz/target/x86_64-unknown-linux-gnu/release/no_panic: Running 1 inputs 1 time(s) each.
Running: fuzz/artifacts/no_panic/crash-7bc4fbe51eb6a77c6a8996e7d2d47ad1e44727b6

thread '<unnamed>' panicked at /home/pigeonf/reading/rc-zip/rc-zip-sync/src/read_zip.rs:214:14:
range start index 5787354386310104582 out of range for slice of length 47
```

**Additional context**

```console
$ cargo +nightly --version
cargo 1.86.0-nightly (2928e3273 2025-02-07)
```

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
fixes #102

constructing a cursor from a `&[u8]` or a `Vec<u8>` will blindly slice the... slice at whatever the provided offset is with no bounds checking which means that it will panic when there's an offset that's beyond the end of the slice. this pr adds explicit bounds checking before constructing a `CursorState` in the `rc-zip-{sync,tokio}` crates that returns an `Error::IO(_)` when out-of-bounds instead of panicking

from reading the code i believe that the `EntryReader` in both crates suffer from the same issue, and i haven't dug in deep enough to see if that one if fixable without api breakage. this issue doesn't happen on the `impl` that uses `positioned_io::Cursor` as the cursor, and that's probably the same for the async version that uses `AsyncRandomAcc...` as the cursor. i don't know how fundamental it is that `&[u8]` and `Vec<u8>` have `&[u8]` as the cursor. if it's possible to switch it to `std::io::Cursor<&[u8]>` then seeking could be infallible like all of the other cursors, and explicit bounds checking wouldn't be necessary as the failure is deferred to when the read happens afaik

### CODE REVIEW

File: rc-zip-sync/tests/regression.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+#[test]
+fn archive_oob_errors_gracefully() {
+    let bad_archive = [
+        0x50u8, 0x4b, 0x6, 0x7, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x50, 0x4b, 0x5,
+        0x6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
+    ];
+    let Err(err) = rc_zip_sync::ReadZip::read_zip(&bad_archive.as_slice()) else {
+        // NOTE(cosmic): `.unwrap_err()` requires `ArchiveHandle` to impl `Debug`, but it doesn't
```
Comment (fasterthanlime) [inline rc-zip-sync/tests/regression.rs]: ugh classic, I hate unwrap_err so much
